// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu83xbvjST-O4_4aoAngWqulgMnOb16Vc',
    appId: '1:777558824880:web:7f973f9ea29a57f883a875',
    messagingSenderId: '777558824880',
    projectId: 'klinik-shoes',
    authDomain: 'klinik-shoes.firebaseapp.com',
    storageBucket: 'klinik-shoes.appspot.com',
    measurementId: 'G-GLE6HG3ZE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo216qp71Ks-KGJvq4w08i-cZkxnqISck',
    appId: '1:777558824880:android:b828d8b03d2c25b883a875',
    messagingSenderId: '777558824880',
    projectId: 'klinik-shoes',
    storageBucket: 'klinik-shoes.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu83xbvjST-O4_4aoAngWqulgMnOb16Vc',
    appId: '1:777558824880:web:91da18fb5680fc0583a875',
    messagingSenderId: '777558824880',
    projectId: 'klinik-shoes',
    authDomain: 'klinik-shoes.firebaseapp.com',
    storageBucket: 'klinik-shoes.appspot.com',
    measurementId: 'G-66CS2K7GMY',
  );
}
